name: flutter_application_api
description: "Enciclopedia Rick y Morty - Flutter API Project"
version: 1.0.0+1
publish_to: 'none'

environment:
  sdk: ^3.9.2

dependencies:
  cached_network_image: ^3.3.1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  http: ^1.2.1
  just_audio: ^0.9.40
  provider: ^6.1.2
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/audio/rick_morty_intro.mp3
    - assets/
    -flutter_application_api/assets/